language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly
jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - addons:
        postgres: 9.4
    - addons:
        postgres: 9.5
    - addons:
        postgres: 9.6
    - addons:
        postgres: 10
    - addons:
        postgres: 11
        apt:
          packages:
            - postgresql-11
            - postgresql-client-11
    - addons:
        postgres: 12
        apt:
          packages:
            - postgresql-12
            - postgresql-client-12
services:
  - mysql
  - postgresql
before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - psql -c "create database test;" -U postgres
before_script:
  - export DB_ADAPTER_MYSQL_TEST_CONFIG='{"db":{"adapter":{"mysql":{"test":{"host":"localhost","username":"root","password":"","dbname":"test"}}}}}';
    export DB_ADAPTER_MYSQLI_TEST_CONFIG='{"db":{"adapter":{"mysqli":{"test":{"host":"localhost","username":"root","password":"","dbname":"test"}}}}}';
    export DB_ADAPTER_PDO_MYSQL_TEST_CONFIG='{"db":{"adapter":{"pdo":{"mysql":{"test":{"host":"localhost","username":"root","password":"","dbname":"test"}}}}}}';
    export DB_ADAPTER_PDO_PGSQL_TEST_CONFIG='{"db":{"adapter":{"pdo":{"pgsql":{"test":{"username":"postgres","password":"","dbname":"test"}}}}}}';
  - phpenv config-rm xdebug.ini || echo "XDebug not enabled"
  - pear install channel://pear.horde.org/Horde_Test
  - pear install -a -B package.xml
script:
  - php $(pear config-get php_dir)/Horde/Test/vendor/phpunit/phpunit/phpunit
